### ISSUE TITLE
Góp ý từ nhóm 1

### ISSUE THREAD

**Issue by huynguyen1999** [huynguyen1999/FinalProject-P4DS#1]

**Comment by phanvoquyen** [comment]
Đầu tiên, nhóm em gửi lời chúc mừng đến nhóm anh vì hoàn thành đồ án thành công và việc phân tích cũng rất công phu kĩ lưỡng khiến nhóm em cũng thực sự rất bất ngờ, tuy nhiên trong đó vẫn còn tồn tại một số khiếm khuyết như sau, mong nhóm anh có thể chỉnh sửa kịp:
1. Về trình bày:
     1.1  Việc trình bày file là chưa đồng nhất, chỗ có viết hoa đầu dòng, chỗ thì chưa, đặc biệt là ở chỗ triển khai câu hỏi
     1.2  Trong một cell code còn chừa các dòng trống lộn xộn, em nghĩ nếu muốn tách bạch code thì có thể tách bởi một dòng 
            trống
     1.3  Trong quá trình xuất kết quả ra ở một cell để check nhóm anh quên xóa đi, để code tiếp phần bên dưới, như vậy dòng 
            này khá thừa ạ, chẳng hạn như ở cell "-xem xét sự thay đổi của số ca theo từng năm" ở mục giới tính
     1.4  Khi thực hiện xong một vài thao tác nào đó, em nghĩ mình nên xuất kết quả ra để người xem hình như được dataframe,... 
           đó có gì, nên tách bạch phần code về xử lí với phần code về vẽ
     1.5  Bên anh chưa vạch ra cell text để chỉ rõ công việc mình cần làm là gì như thầy đã nói ở file hướng dẫn đồ án khiến việc 
           đọc của người khác thực sự khó khăn ạ, chẳng hạn như câu hỏi số 1 một số phần kiến thức mà nhóm anh sử dụng khiến   
           em khó khăn trong việc hình dung là nhóm đang làm gì ạ :'( (cũng có thể là do kiến thức em còn hẹp quá ạ)
    1.6  Em nghĩ nhóm nến xuất kết quả ra cho người xem thấy chứ không cần tạo assert như thầy ạ
    1.7  Nhóm anh chưa có link tài liệu tham khảo để nhóm em đọc đối chiếu ạ 
2. Về nội dung và cách thức thực hiện:
     2.1 Về phần tiền xử lí, khám phá dữ liệu em thấy nhóm anh làm tốt ạ, chỗ trực quan để xét những năm mà các nước có số ca 
           tự tử bằng 0 rất đẹp và công phu, em nhất trí về việc xóa đi các năm không có ca tự tử cũng như những quốc gia có mẫu 
           thu thập ít 
     2.2 Về câu hỏi số 1, em thấy nhóm làm rất công phu về phần trực quan, vì quỹ thời gian ngắn nên em cũng chỉ đọc hiểu tóm 
           lược về phần biểu đồ, có một số kiến thức em vẫn chưa hiểu rõ như np.polyfit, nên biểu đồ đầu tiên em chưa hiểu lắm 
           (chắc là đi vẽ hệ số coef của từng quốc gia), về phần trích từng quốc gia có xu hướng tăng giảm thuộc top, em nghĩ sau 
           khi trực quan nhóm nên có nhận xét, sumary lại cho người đọc dễ hình dung được lại vấn đề , chỗ này có dòng code này ` 
           ax[row, col].plot(years,suicides,'o', years, coef[0]*years + coef[1],'--k', color=colors[index])` chỗ coef em chưa hiểu lắm, em 
           đang nghĩ nó là đường hồi quy theo polyfit phải không ạ. Tóm lại thì phần này em thấy việc xử lí của anh cung cấp được 
           cho người đọc về xu hướng tự tử của các quốc gia theo năm, tuy nhiên cần có thêm kết luận về các nước top mà anh đã 
           trích xuất ra thêm, vì thế anh có thể bổ sung câu hỏi thêm là, "đâu là top 5/10 quốc gia có tỉ lệ tăng/giảm tỉ lệ tự tử theo 
           năm mạnh nhất"
    2.3  Về câu hỏi số 2, ở phần khảo sát xu hướng tự tự và GDP em thấy việc sử dụng biểu đồ đường là phù hợp, chuẩn hóa khi 
           chia cho max cũng ổn, tuy nhiên biểu đồ cần thêm xlabel, ylabel, chỗ khảo sát với tổng số ca tự tử và số ca tự tử/100k 
           dân thì em nghĩ có thể bỏ bớt đi một cái cũng được, vì em thấy nó cũng khá tương đồng. Về biểu đồ "Total Suicides vs 
           GPD per capita" em thấy nhận xét của nhóm anh về xu hướng chung như vậy nó cũng chưa ổn lắm ạ, vì em thấy dữ liệu 
           nó cứ dâng lên rồi hạ xuống như hình tam giác ạ. Phần top 6 quốc gia em nghĩ ổn. Phần trực quan của Nhật với Mỹ nó lại 
           không được khớp lắm với phần trực quan top 6 quốc gia ạ, vì ở top 6 quốc gia trục Ox được vẽ theo GDP, nhưng trực 
           quan Nhật với Mỹ thì lại được vẽ theo năm
    2.4  Câu hỏi số 3 nhóm anh đặt là "3/ giới tính nào có xu hướng tự tử nhiều hơn, hơn bao nhiêu lần?" , theo em để khẳng định 
           được xu hướng thì phải có số ca tự tử của nam/tổng số nam và số ca tự tử của nữ/tổng số nữ, nếu câu hỏi được chỉnh sửa 
           thành "giới tính nào có số ca tự tử nhiều hơn" thì sẽ hợp lí hơn. Thêm vào đó câu hỏi không tương ứng với phần phân 
           tích của nhóm, với câu hỏi nhắm tới việc xét nam/nữ bên nào tự tử nhiều hơn thì em nghĩ việc phân tích chỉ cần dừng lại 
           ở chỗ tổng số ca tự tử theo từng năm của mỗi giới là đủ, nó cho người đọc thấy được xu hướng trên thế giới là được. Với 
           việc phân tích thêm tại mỗi quốc gia và tại mỗi nhóm tuổi là không cần thiết lắm, nếu anh muốn kĩ hơn về phần này, em 
           nghĩ anh nên mở rộng câu hỏi của anh ra cho phù hợp. Và em thấy việc khảo sát trên toàn dân với trên 100k dân nó cũng 
           khá tương đồng nên nhóm anh có thể loại bỏ bớt một cái cũng được ạ. Tựu chung lại việc kết luận về tỷ lệ tự tử ở nam 
           cao hơn nữ 3-4 lần là chưa hợp lí với lí do em đã nói ở câu đầu tiên của đoạn 2.4. Còn phần trên thực tế anh bình luận thì 
           em không biết đúng hay sai 

Trên đây là phần nhận xét của em, chúc nhóm anh chỉnh sửa đồ án thành công ạ <3

**Comment by huynguyen1999** [comment]
Okay, mình rất cảm ơn những góp ý khá chi tiết của bạn nha, mình sẽ cố gắng chỉnh sửa dựa vào đó trong ngày hôm nay.
P/s: ở câu hỏi 1, np.polyfit đúng là tìm ra đường hồi quy tuyến tính và 'coef' ở đây sẽ chứa intercept và bias.

**Comment by caophuccp** [comment]
# Một số nhận xét về đồ án của nhóm 2
## Trình bày
- Trình bày chưa đồng nhất, còn chứa một số cell vô nghĩa.
- Nhóm dùng `assert` để thay thế cho câu trả lời không thích hợp (`assert` thường dùng khi debug với ý nghĩa khẳng định điều gì đó).
## Nội dung
### 1. Xu hướng tăng giảm của tỉ lệ tự tử trên từng quốc gia
- Nhóm đưa ra khá nhiều biểu đồ nhưng lại không có ghi chú, kết luận. 
- Biểu đồ đầu tiên rất khó hiểu, ý nghĩa của trục tung, trục hoàng không có.


### 2. Liệu giàu có có giúp làm giảm tỷ lệ tự tử không?
- Sau biểu đồ `Total Suicides vs GPD_per_capita`, nhóm có nhận xét `từ sau năm 1995, sau khi kinh tế toàn cầu đi lên thì ta thấy tổng số ca tự tử đã bắt đầu giảm. => Kinh tế phát triển, đời sống đi lên góp phần giảm thiểu số ca tự tử.`. Tuy nhiên đường `total_suicide` sau năm 1995 không ổn định, tăng giảm liên tục và sau năm 2010 tăng dần, trước năm 1995 cũng tăng dần. Như vậy nhận xét này của nhóm có vẻ chưa được rõ ràng.

- Sau biểu đồ  `Total Suicides vs GPD per capita`  nhóm kết luận `những nước có GDP thấp thì có số ca tự tử cao còn ngược lại những nước có GPD cao thì số ca tự tử lại thấp` nhưng đường `suicide_rate` lại nâng lên rồi hạ xuống. Như vậy nhận xét này của nhóm có vẻ chưa được rõ ràng.

### 3. Giới tính nào có xu hướng tự tử nhiều hơn, hơn bao nhiêu lần?
- Nhóm trình bày khá nhiều và chi tiết, tuy nhiên để trả lời cho câu hỏi số 3 có vẻ không cần chi tiết như vậy.
- Nhóm đưa ra thông tin `Trong thực tế thì Nữ có xu hướng tự tử nhiều hơn Nam nhưng cách thức tự tử lại có xu hướng ít bạo lực hơn nên tỷ lệ được cấp cứu thành công nhiều hơn nam` lại thiếu dẫn chứng, cũng không thể xác nhận được.

# Cuối cùng chúc nhóm có đồ án thành công
